name: Build on Windows

on:
  workflow_call:
    inputs:
      qt-version:
        required: true
        type: string
      qt-arch:
        required: true
        type: string
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Build
        uses: ./.github/actions/qt-build
        with:
          qt-version: ${{ inputs.qt-version == '' && inputs.qt-version || '6.6.0' }}
          qt-arch: ${{ inputs.qt-arch == '' && inputs.qt-arch || 'win64_msvc2019_64' }}
          cxx-compiler: cl
          c-compiler: cl
          build-dir: ${{ runner.workspace }}/build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: win-build
          path: ${{ runner.workspace }}/build
