name: Publish windows binaries
run-name: ${{ github.actor }} is created/modify release
on: 
  release:
    types: [created,edited]

env:
  QT_VER: 6.6.0
  QT_ARCH: win64_msvc2019_64

jobs:
  build:
    uses: ./.github/workflows/win-build.yml
    with: # workaround of bug with env
      qt-version: 6.6.0
      qt-arch: win64_msvc2019_64
  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with: 
          version: ${{ env.QT_VER }}
          arch: ${{ env.QT_ARCH }}
          cache: true
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: win-build
          path: build
      - name: Extract binaries from build
        run: |
          new-item -path "deploy" -type directory
          move-item -path build\lab.exe -destination deploy
      - name: Deploy libs
        run:  |
          windeployqt --qmldir build --release --no-translations --no-system-d3d-compiler -no-opengl-sw deploy\lab.exe
      - name: Archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'win-release.zip'
          path: deploy/
      - name: Upload release
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: win-release.zip
          path: win-release.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/zip
